import React from "react";
import CommonLayout from "../(withCommonLayout)/layout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Deshi Bazar | About",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <CommonLayout>
      <h2>This is about us page</h2>
    </CommonLayout>
  );
};

export default About;
