import React from "react";
import CommonLayout from "../(withCommonLayout)/layout";
import type { Metadata } from "next";
import { TProduct } from "@/types";
import Container from "@/components/ui/Container";
import ProductCard from "@/components/ui/ProductCard";

export const metadata: Metadata = {
  title: "Deshi Bazar | Flash Sale",
  description: "Generated by create next app",
};

const FlashSale = async () => {
  const res = await fetch("http://localhost:5000/api/v1/products");
  const products = await res.json();

  const flashSaleProducts = products.filter(
    (item: TProduct) => item.flash_sale == true
  );

  return (
    <CommonLayout>
      <Container className="px-8 mt-10 mb-16">
        <div>
          <h2 className="text-3xl font-bold">Flash Sale</h2>
        </div>

        <div className="my-10">
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-5 justify-items-center">
            {flashSaleProducts.map((item: TProduct) => (
              <ProductCard
                key={item._id}
                product={item}
                showRating={false}
              ></ProductCard>
            ))}
          </div>
        </div>
      </Container>
    </CommonLayout>
  );
};

export default FlashSale;
