import React from "react";
import CommonLayout from "../(withCommonLayout)/layout";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Deshi Bazar | contact",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <CommonLayout>
      <h2>This is contact us page</h2>
    </CommonLayout>
  );
};

export default Contact;
