import React from "react";
import CommonLayout from "../(withCommonLayout)/layout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Deshi Bazar | Categories",
  description: "Generated by create next app",
};

const Categories = () => {
  return (
    <CommonLayout>
      <h3>This is categories page</h3>
    </CommonLayout>
  );
};

export default Categories;
