import React from "react";
import CommonLayout from "../(withCommonLayout)/layout";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Deshi Bazar | products",
  description: "Generated by create next app",
};
const Products = () => {
  return (
    <CommonLayout>
      <h2>This is products page</h2>
    </CommonLayout>
  );
};

export default Products;
