import React from "react";
import CommonLayout from "../(withCommonLayout)/layout";
import type { Metadata } from "next";
import { TProduct } from "@/types";
import Container from "@/components/ui/Container";
import ProductCard from "@/components/ui/ProductCard";
// import useCountDown from "@/lib/useCountDown";

export const metadata: Metadata = {
  title: "Deshi Bazar | Flash Sale",
  description: "Generated by create next app",
};

const ProductsPage = async () => {
  const res = await fetch(
    "https://deshi-bazar-server.vercel.app/api/v1/products?category "
  );
  const products = await res.json();

  return (
    <CommonLayout>
      <Container className="px-8 mt-10 mb-16">
        <div>
          <h2 className="text-3xl font-semibold">Our Collection of Products</h2>
        </div>

        <div className="my-10">
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-5 justify-items-center">
            {products.map((item: TProduct) => (
              <ProductCard
                key={item._id}
                product={item}
                showRating={false}
              ></ProductCard>
            ))}
          </div>
        </div>
      </Container>
    </CommonLayout>
  );
};

export default ProductsPage;
